services:
  postgres-db:
    image: postgres:15
    container_name: postgres_db2
    environment:
      POSTGRES_USER: hello
      POSTGRES_PASSWORD: hello
      POSTGRES_DB: hibernate
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: