datasource:
  url: jdbc:postgresql://localhost:5432/hibernate
  driver: org.postgresql.Driver
  username: hello
  password: hello

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  format_sql: true
  physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
liquibase:
  changelog: classpath:db/changelog/db.changelog-master.yaml
